const AUTHENTICATE_ROUTE = {
    ONBOARD: '@AUTHENTICATE_ROUTE/ONBOARD',
    LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
    REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
    FORGOT_PASS: '@AUTHENTICATE_ROUTE/FORGOT_PASS',
    SEND_OTP: '@AUTHENTICATE_ROUTE/SEND_OTP',
    CHANGE_PASS: '@AUTHENTICATE_ROUTE/CHANGE_PASS',
    FILL_PROFILE: '@AUTHENTICATE_ROUTE/FILL_PROFILE',
    LANDING: '@AUTHENTICATE_ROUTE/LANDING',
};
const APP_ROUTE = {
    HOME: '@APP_ROUTE/HOME',
};


const TAB_NAVIGATION_ROOT = {

};

export { TAB_NAVIGATION_ROOT, AUTHENTICATE_ROUTE, APP_ROUTE };
